app:
  database:
    vendor: postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: postgres
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration/${app.database.vendor}
  ai:
    openai:
      base-url: http://localhost:1234
      api-key: lm-studio
      embedding:
        options:
          model: text-embedding-qwen3-embedding-0.6b
      chat:
        options:
          model: qwen3-4b-instruct-2507

server:
  error:
    include-message: always

sample-loader:
  enabled: true
