app:
  database:
    vendor: postgres
  semantic-search:
    similarity-threshold: 0.75

spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: postgres
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration/${app.database.vendor}
  autoconfigure:
    exclude: org.springframework.ai.vectorstore.mariadb.autoconfigure.MariaDbStoreAutoConfiguration
  ai:
    openai:
      base-url: http://localhost:1234
      api-key: lm-studio
      embedding:
        options:
          model: text-embedding-qwen3-embedding-0.6b
          dimensions: 1024
      chat:
        options:
          model: qwen3-4b-instruct-2507
    vectorstore:
      pgvector:
        enabled: true
        initialize-schema: true
        id-type: TEXT

server:
  error:
    include-message: always

sample-loader:
  enabled: true
