app:
  database:
    vendor: postgres
  semantic-search:
    similarity-threshold: 0.5
  document-indexing:
    worker:
      fixed-delay-ms: 1000
      batch-size: 10
      base-backoff-ms: 2000
      summarize-threshold-chars: 1200

spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: postgres
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration/${app.database.vendor}
  ai:
    openai:
      base-url: http://localhost:1234
      api-key: lm-studio
      embedding:
        options:
          model: text-embedding-qwen3-embedding-0.6b
          dimensions: 1024
      chat:
        options:
          model: qwen/qwen3-4b-2507
    vectorstore:
      pgvector:
        enabled: true
        initialize-schema: true
        id-type: TEXT

server:
  error:
    include-message: always

sample-loader:
  enabled: true
